/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    ColorSwitchingCube: typeof import('./components/ColorSwitchingCube.vue')['default']
    Cube: typeof import('./components/Cube.vue')['default']
    EarthRotation: typeof import('./components/EarthRotation.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    RotatingCube: typeof import('./components/RotatingCube.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
